# W-12 Linear Algebra

In [1]:
# Scalars
a = 12

In [2]:
a

12

In [3]:
# Vectors
l = [1,2,3]

In [4]:
l

[1, 2, 3]

In [ ]:
# We also have matrices

## Linear algebra with Numpy and Scipy

In [5]:
import numpy as np
import scipy.linalg as la

In [6]:
# Scalar 
a = 12

In [7]:
# Vectors
b = np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [8]:
b.shape

(4,)

In [9]:
b.ndim

1

In [10]:
b.size

4

In [12]:
# Matrices

M = np.array([[1,2],[3,7],[-1,5]])
M

array([[ 1,  2],
       [ 3,  7],
       [-1,  5]])

In [13]:
M.ndim

2

In [14]:
M.shape

(3, 2)

In [15]:
M.size

6

In [16]:
# Getting a vector from a matrix
col = M[:,1]
col

array([2, 7, 5])

In [18]:
col.ndim

1

In [19]:
col.shape

(3,)

## Matrix operations and functions

In [20]:
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

### Arithmetic operations

Al of the basic operations are defined, +, -, /, *, $**$.

In [21]:
M*M # elementwise multiplication

array([[ 1,  4],
       [ 9, 16]])

### Matrix multiplication

In [22]:
M @ M

array([[ 7, 10],
       [15, 22]])

#### Example

Let's compute $2I + 3A - AB$

$$
I = \begin{bmatrix}
1 & 0 \\
0 & 1
\end{bmatrix}
\ \ \ \
A = \begin{bmatrix}
1 & 3 \\
-1 & 7
\end{bmatrix}
\ \ \ \
B = \begin{bmatrix}
5 & 2 \\
1 & 2
\end{bmatrix}
$$

In [25]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [26]:
A = np.array([[1,3],[-1,7]])
A

array([[ 1,  3],
       [-1,  7]])

In [28]:
B=np.array([[5,2],[1,2]])
B

array([[5, 2],
       [1, 2]])

In [29]:
2*I + 3*A - A@B

array([[-3.,  1.],
       [-5., 11.]])

### Transpose

In [30]:
M

array([[1, 2],
       [3, 4]])

In [31]:
M.T

array([[1, 3],
       [2, 4]])

In [32]:
M @ M.T # symmetric matrix

array([[ 5, 11],
       [11, 25]])

### Inverse

In [33]:
M

array([[1, 2],
       [3, 4]])

In [34]:
la.inv(M)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [35]:
M @ la.inv(M)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

### Trace

In [36]:
M

array([[1, 2],
       [3, 4]])

In [37]:
np.trace(M)

5

### Determinant

$$
\det{A} = |A| = \begin{vmatrix} a & b \\ c & d \end{vmatrix} = ad - bc
$$

In [38]:
M

array([[1, 2],
       [3, 4]])

In [40]:
la.det(M)

-2.0