# Popular Python Packages

### Examples from * and **

In [1]:
m = [1,2,3,4,5]

In [2]:
print(m)

[1, 2, 3, 4, 5]


In [3]:
print(*m)

1 2 3 4 5


In [4]:
dates = {"year":"2021", "month":"06", "day":"28"}

In [5]:
dates

{'year': '2021', 'month': '06', 'day': '28'}

In [9]:
filename = "{year}-{month}-{day}.txt".format(**dates)

In [10]:
filename

'2021-06-28.txt'

## Numpy

In [11]:
import numpy as np

In [12]:
a = np.array([1,2,3])

In [13]:
a

array([1, 2, 3])

In [14]:
type(a)

numpy.ndarray

In [15]:
# Regular python
a = [1,2,3]
b = [4,5,6]

In [16]:
a+b

[1, 2, 3, 4, 5, 6]

In [17]:
# With numpy
a = np.array([1,2,3])
b = np.array([4,5,6])

In [18]:
a+b

array([5, 7, 9])

In [19]:
# Create an array with arange
my_arr = np.arange(15)

In [20]:
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
my_matrix = my_arr.reshape(3,5)
my_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
my_matrix.shape

(3, 5)

In [25]:
my_matrix.dtype.name

'int64'

In [26]:
my_matrix.size

15

In [27]:
# Create a matrix with a list of tuples

b = np.array([(1,2,3),(4,5,6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# Matrix of zeros
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
# Matrix of ones
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [33]:
# Create an empty matrix (weird behavior) (don't use this)

np.empty((4,3))

array([[-1.49166815e-154, -1.49166815e-154,  5.43472210e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000, -1.49166815e-154],
       [-1.49166815e-154,  3.45845952e-323,  5.04621361e+180]])

In [34]:
## Indexing in numpy
b = np.array([(1,2,3),(4,5,6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
b[0]

array([1, 2, 3])

In [39]:
2 == b[0][1]

True

In [41]:
# Loop over a numpy array
for i in b:
    print(i)

[1 2 3]
[4 5 6]


In [42]:
for i in b[0]:
    print(i)

1
2
3


In [45]:
# With Python
[1,2,3]**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [46]:
np.array([1,2,3])**2

array([1, 4, 9])

## Pandas

In [47]:
import pandas as pd

In [48]:
df = pd.read_csv("bikes.csv")

In [49]:
df.head()

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2  2011-01-01 02:00:00       1        0           0        1  9.02  13.635   
3  2011-01-01 03:00:00       1        0           0        1  9.84  14.395   
4  2011-01-01 04:00:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40  
2        80        0.0       5          27     32  
3        75        0.0       3          10     13  
4        75        0.0       0           1      1

In [52]:
df[4:8]

datetime  season  holiday  workingday  weather  temp   atemp  \
4  2011-01-01 04:00:00       1        0           0        1  9.84  14.395   
5  2011-01-01 05:00:00       1        0           0        2  9.84  12.880   
6  2011-01-01 06:00:00       1        0           0        1  9.02  13.635   
7  2011-01-01 07:00:00       1        0           0        1  8.20  12.880   

   humidity  windspeed  casual  registered  count  
4        75     0.0000       0           1      1  
5        75     6.0032       0           1      1  
6        80     0.0000       2           0      2  
7        86     0.0000       1           2      3

In [53]:
df.dtypes

datetime       object
season          int64
holiday         int64
workingday      int64
weather         int64
temp          float64
atemp         float64
humidity        int64
windspeed     float64
casual          int64
registered      int64
count           int64
dtype: object

In [54]:
df["temp"] # Pandas series

0         9.84
1         9.02
2         9.02
3         9.84
4         9.84
         ...  
10881    15.58
10882    14.76
10883    13.94
10884    13.94
10885    13.12
Name: temp, Length: 10886, dtype: float64

In [55]:
df[["temp"]]

temp
0       9.84
1       9.02
2       9.02
3       9.84
4       9.84
...      ...
10881  15.58
10882  14.76
10883  13.94
10884  13.94
10885  13.12

[10886 rows x 1 columns]